apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "m537-voice-gateway.fullname" . }}
  labels:
    {{- include "m537-voice-gateway.labels" . | nindent 4 }}
data:
  PROJECTS_BASE_PATH: {{ .Values.config.projectsBasePath | quote }}
